---

- name: Testing playbook for create token
  hosts: all
  gather_facts: false

  tasks:
    - name: Create a new token using username/password
      ansible.controller.token:
        description: Temp token
        scope: write
        state: present
        controller_username: "{{ api_username }}"
        controller_password: "{{ api_password }}"
        controller_host: "{{ tower_host | default('http://127.0.0.1') }}"
        validate_certs: false
    
    - name: Create team
      ansible.controller.team:
        name: Number 1
        description: Team Description
        organization: Default
        state: present
        controller_oauthtoken: "{{ controller_token }}"
        controller_host: "{{ tower_host | default('http://127.0.0.1') }}"
        validate_certs: false

    - name: Call Automation Controller API
      when: ansible_facts['controller_token'] is defined and
            ansible_facts['controller_token']['token'] is defined
      block:
        - name: List running jobs
          register: testing_jobs
          ignore_errors: true
          environment:
            CONTROLLER_OAUTH_TOKEN: "{{ ansible_facts['controller_token']['token'] }}"
          ansible.controller.job_list:
            status: successful
            query:
              playbook: "hello_world.yml"
            #aap_token: "{{ ansible_facts['aap_token']['token'] }}"
            controller_host: "{{ tower_host | default('http://127.0.0.1') }}"
            validate_certs: false

        - name: Debug token
          ansible.builtin.debug:
            var: ansible_facts['controller_token']
            verbosity: 3
